package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Alfonso
 */
public class AboutUs extends javax.swing.JFrame {

    /**
     * Creates new form AcercaDeFrame
     */
    public AboutUs() {
        initComponents();
    estadioImage.addComponentListener(new ComponentAdapter() {
        @Override
        public void componentResized(ComponentEvent e) {
            ajustarImagen();
        }
    });
    ajustarImagen(); // Forzar el ajuste inicial de la imagen
        System.out.println(estadioImage.getWidth());
        System.out.println(estadioImage.getHeight());
        System.out.println(this.getWidth());
        System.out.println(this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblTeam = new javax.swing.JLabel();
        lblIntro = new javax.swing.JLabel();
        lblAndres = new javax.swing.JLabel();
        lblDavid = new javax.swing.JLabel();
        lblDiseño = new javax.swing.JLabel();
        lblAlfonso = new javax.swing.JLabel();
        lblSebastian = new javax.swing.JLabel();
        lblGerente = new javax.swing.JLabel();
        lblUI = new javax.swing.JLabel();
        lblCreaativo = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        estadioImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(627, 419));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBackground.setBackground(new java.awt.Color(0, 0, 0));
        pnlBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pnlBackground.setPreferredSize(new java.awt.Dimension(626, 417));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTeam.setFont(new java.awt.Font("Papyrus", 0, 20)); // NOI18N
        lblTeam.setForeground(new java.awt.Color(204, 204, 204));
        lblTeam.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTeam.setText("Time Treep Team");
        pnlBackground.add(lblTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 165, 440, 30));

        lblIntro.setBackground(new java.awt.Color(255, 255, 255));
        lblIntro.setFont(new java.awt.Font("Blackadder ITC", 0, 60)); // NOI18N
        lblIntro.setForeground(new java.awt.Color(204, 204, 204));
        lblIntro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIntro.setText("Movimiento Táctico");
        pnlBackground.add(lblIntro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 460, 80));

        lblAndres.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        lblAndres.setForeground(new java.awt.Color(204, 204, 204));
        lblAndres.setText("Andres Forero");
        pnlBackground.add(lblAndres, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 200, 30));

        lblDavid.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        lblDavid.setForeground(new java.awt.Color(204, 204, 204));
        lblDavid.setText("David Gutierrez");
        pnlBackground.add(lblDavid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 200, 30));

        lblDiseño.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        lblDiseño.setForeground(new java.awt.Color(204, 204, 204));
        lblDiseño.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiseño.setText("Director de Diseño");
        pnlBackground.add(lblDiseño, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 200, 30));

        lblAlfonso.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        lblAlfonso.setForeground(new java.awt.Color(204, 204, 204));
        lblAlfonso.setText("Alfonso Cohen");
        pnlBackground.add(lblAlfonso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 200, 30));

        lblSebastian.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        lblSebastian.setForeground(new java.awt.Color(204, 204, 204));
        lblSebastian.setText("Sebastian Cotes");
        pnlBackground.add(lblSebastian, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 200, 30));

        lblGerente.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        lblGerente.setForeground(new java.awt.Color(204, 204, 204));
        lblGerente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGerente.setText("Gerente del Proyecto");
        pnlBackground.add(lblGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 30));

        lblUI.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        lblUI.setForeground(new java.awt.Color(204, 204, 204));
        lblUI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUI.setText("Director UI/UX");
        pnlBackground.add(lblUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 200, 30));

        lblCreaativo.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        lblCreaativo.setForeground(new java.awt.Color(204, 204, 204));
        lblCreaativo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCreaativo.setText("Director Creativo");
        pnlBackground.add(lblCreaativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, 30));

        lblCerrar.setBackground(new java.awt.Color(102, 0, 0));
        lblCerrar.setFont(new java.awt.Font("Papyrus", 0, 36)); // NOI18N
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setText("×");
        lblCerrar.setOpaque(true);
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblCerrarMouseReleased(evt);
            }
        });
        pnlBackground.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 2, 40, 25));

        estadioImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/estadio.png"))); // NOI18N
        pnlBackground.add(estadioImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        getContentPane().add(pnlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseReleased
        // TODO add your handling code here:
        if (lblCerrar.contains(evt.getX(), evt.getY())) {
            lblCerrarMouseClicked(evt);
        }
    }//GEN-LAST:event_lblCerrarMouseReleased

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        // TODO add your handling code here:

        lblCerrar.setBackground(new Color(102, 0, 0));
        lblCerrar.setForeground(Color.black);
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        // TODO add your handling code here:
        lblCerrar.setBackground(new Color(204, 0, 0));
        lblCerrar.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked
private void ajustarImagen() {
        // Cargar la imagen
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/recursos/estadio.png"));

        // Obtener las dimensiones del JLabel
        int width = estadioImage.getWidth();
        int height = estadioImage.getHeight();

        // Redimensionar la imagen para que se ajuste al JLabel
        Image image = imageIcon.getImage();
        Image scaledImage = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Establecer la imagen redimensionada como icono del JLabel
        estadioImage.setIcon(scaledIcon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estadioImage;
    private javax.swing.JLabel lblAlfonso;
    private javax.swing.JLabel lblAndres;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCreaativo;
    private javax.swing.JLabel lblDavid;
    private javax.swing.JLabel lblDiseño;
    private javax.swing.JLabel lblGerente;
    private javax.swing.JLabel lblIntro;
    private javax.swing.JLabel lblSebastian;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JLabel lblUI;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
