/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import static java.awt.Color.BLUE;
import static java.awt.Color.WHITE;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import java.awt.Color;
import java.util.List;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/**
 *
 * @author andre
 */
public class Menu_Principal extends javax.swing.JPanel {

    private Timer colorChangeTimer;
    private Color[] colors = {Color.RED, Color.GREEN, Color.BLUE, Color.ORANGE, Color.MAGENTA}; // Colores a usar
    private int currentColorIndex = 0; // Índice del color actual

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        colorChangeTimer = new Timer(3000, e -> cambiarColorTexto());
        colorChangeTimer.start(); // Inicia el temporizador
        estadioImage.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                ajustarImagen();
            }
        });

    }

    private void transitarColor(Color startColor, Color endColor, int steps) {
        SwingWorker<Void, Color> worker = new SwingWorker<Void, Color>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= steps; i++) {
                    int red = (int) (startColor.getRed() + (endColor.getRed() - startColor.getRed()) * (i / (float) steps));
                    int green = (int) (startColor.getGreen() + (endColor.getGreen() - startColor.getGreen()) * (i / (float) steps));
                    int blue = (int) (startColor.getBlue() + (endColor.getBlue() - startColor.getBlue()) * (i / (float) steps));
                    publish(new Color(red, green, blue)); // Publica el color intermedio
                    try {
                        Thread.sleep(20); // Espera 20 ms para suavizar la transición
                    } catch (InterruptedException e) {
                        break;
                    }
                }
                return null;
            }

            @Override
            protected void process(List<Color> colors) {
                // Cambia el color del texto en el JLabel
                for (Color color : colors) {
                    jLabel1.setForeground(color);
                }
            }
        };
        worker.execute(); // Inicia el worker
    }

    private void cambiarColorTexto() {
        Color startColor = jLabel1.getForeground();
        Color endColor = colors[currentColorIndex];

        // Llama al método de transición
        transitarColor(startColor, endColor, 30); // 30 pasos para la transición

        currentColorIndex = (currentColorIndex + 1) % colors.length; // Cicla a través de los colores
    }

    private void ajustarImagen() {
        // Cargar la imagen
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/recursos/estadio.png"));

        // Obtener las dimensiones del JLabel
        int width = estadioImage.getWidth();
        int height = estadioImage.getHeight();

        // Redimensionar la imagen para que se ajuste al JLabel
        Image image = imageIcon.getImage();
        Image scaledImage = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Establecer la imagen redimensionada como icono del JLabel
        estadioImage.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        aboutUsButton = new javax.swing.JButton();
        aboutTheGameButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        exitButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        estadioImage = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(626, 417));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startButton.setText("Start");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startButtonMouseEntered(evt);
            }
        });
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 120, 50));

        aboutUsButton.setText("About Us");
        aboutUsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsButtonMouseClicked(evt);
            }
        });
        aboutUsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsButtonActionPerformed(evt);
            }
        });
        add(aboutUsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 120, 50));

        aboutTheGameButton.setText("About The Game");
        aboutTheGameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutTheGameButtonMouseClicked(evt);
            }
        });
        aboutTheGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutTheGameButtonActionPerformed(evt);
            }
        });
        add(aboutTheGameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 120, 50));

        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 255));
        exitButton.setText("X");
        exitButton.setBorder(null);
        exitButton.setContentAreaFilled(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitButtonMouseReleased(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 20, 20));

        exitButton2.setText("Exit");
        exitButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButton2MouseEntered(evt);
            }
        });
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });
        add(exitButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, 50));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel1.setText("MOVIMIENTO TÁCTICO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        estadioImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/estadio.png"))); // NOI18N
        estadioImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadioImageMouseClicked(evt);
            }
        });
        add(estadioImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void estadioImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadioImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_estadioImageMouseClicked

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        Main main = new Main();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_startButtonActionPerformed

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonMouseClicked

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setForeground(WHITE);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseReleased

    }//GEN-LAST:event_exitButtonMouseReleased

    private void aboutTheGameButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutTheGameButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutTheGameButtonMouseClicked

    private void aboutTheGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutTheGameButtonActionPerformed
        About_Us au = null;
        try {
            au = new About_Us();
        } catch (IOException ex) {
            Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        au.setVisible(true);

    }//GEN-LAST:event_aboutTheGameButtonActionPerformed

    private void startButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseEntered

    }//GEN-LAST:event_startButtonMouseEntered

    private void exitButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButton2MouseClicked

    private void exitButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButton2MouseEntered

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButton2ActionPerformed

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setForeground(BLUE);
    }//GEN-LAST:event_exitButtonMouseExited

    private void aboutUsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutUsButtonMouseClicked

    private void aboutUsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsButtonActionPerformed
        System.out.println("Button clicked"); // Depuración
        AboutUs au = new AboutUs();
        au.setVisible(true);

    }//GEN-LAST:event_aboutUsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutTheGameButton;
    private javax.swing.JButton aboutUsButton;
    private javax.swing.JLabel estadioImage;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
