package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import modelo.Circulo;
import modelo.Formaciones;
import static modelo.Formaciones.s352;
import static modelo.Formaciones.s4231;
import static modelo.Formaciones.s433;
import static modelo.Formaciones.s442;

/**
 *
 * @author Alfonso
 */
public class pnlJugadores extends javax.swing.JPanel {

    ArrayList<Circulo> jugadores;

    /**
     * Creates new form pnlCancha
     */
    public pnlJugadores() {
        initComponents();
        jugadores = new ArrayList<>();
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jugadores.add(new Circulo(evt.getX(), evt.getY(), 20, Color.BLUE));
        System.out.println(evt.getX() + ", " + evt.getY());
        revalidate();
        repaint();
        this.getParent().repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        for (Circulo jugador : jugadores) {
            jugador.dibujar(g);
        }
    }

    private void dibujarCirculos(Formaciones formacion) {
        for (int[] pos : formacion.getFormacion()) {
            jugadores.add(new Circulo(pos[0], pos[1], 15, Color.red));
        }
    }

    public void mostraJugadores(int formacion) {
        jugadores.clear();
        switch (formacion) {
            case 442:
                dibujarCirculos(s442);
                break;

            case 4231:
                dibujarCirculos(s4231);
                break;

            case 352:
                dibujarCirculos(s352);
                break;

            case 433:
                dibujarCirculos(s433);
                break;

            default:
                System.out.println("Formación no válida.");
        }
        repaint();
    }

}
