package radar;

import java.awt.Graphics;
import radar.Radar;

/**
 *
 * @author Alfonso
 */
public class Rad extends javax.swing.JPanel {

    radar.Radar radar;

    /**
     * Creates new form Rad
     */
    public Rad() {
        initComponents();
        int radio = 80; // Ajusta el tamaño del radio como prefieras
        radar = new Radar(200, 200, radio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        radar.dibujarRadar(g);
        radar.dibujarGrafico(g);
    }

    public void actualizarGrafico(int velocidad, int posesion, int remate) {
        radar.asignarDatosRadar(velocidad, posesion, remate);
        repaint(); // Repinta el panel para mostrar el nuevo gráfico
    }

}
